import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import React from 'react'
import { useRouter } from 'next/dist/client/router'
import { ROUTES } from '../constants/routes'
import { Box, Button, Center } from '@chakra-ui/react'
import Link from 'next/link'
import MainPage from '../components/MainPage'
import HomeLayout from '../components/common/@Layout/HomeLayout'
const Home: NextPage = () => {
  const router = useRouter();

  return (
    <>
    <Head>
      <title>Front Mission</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomeLayout title="메인 페이지 입니다." content={<MainPage content='asdf' />}/>
    </>
  )
}

export default Home
